export const entertainmentData = [
  {
    viewAllText: "View All",
    sectionName: "Entertainment",
    categoryImage: "/entertainment/category/atlantic.png",
    bannerImage: "/entertainment/banners/gameofthrones.jpg",
    title: "Game of Thrones",
    description:
      "The all-conquering, multi-Emmy-winning adaption of George R R Martin's rich yet brutal fantasy saga.",
    classification: "",
    classAge: "18",
    duration: "8 Seasons",
    year: "",
    genre: "Drama",
    altText: "Game of Thrones",
  },
  {
    viewAllText: "View All",
    sectionName: "Entertainment",
    categoryImage: "/entertainment/category/atlantic.png",
    bannerImage: "/entertainment/banners/thepenguin.jpg",
    title: "The Penguin",
    description:
      "In the next chapter in Matt Reeves' epic The Batman saga, this thrilling crime drama follows Oswald 'OZ' Cobb's quest for power and control in a fractured Gotham City.",
    classification: "",
    classAge: "18",
    duration: "8 Episodes",
    year: "",
    genre: "Drama",
    altText: "The Penguin",
  },
  {
    viewAllText: "View All",
    sectionName: "Entertainment",
    categoryImage: "/entertainment/category/atlantic.png",
    bannerImage: "/entertainment/banners/houseofthedragon.jpg",
    title: "House of the Dragon",
    description:
      "Based on George R R Martin's Fire & Blood, the BAFTA-winning series, set 200 years before the events of Game of Thrones, tells the story of House Targaryen.",
    classification: "",
    classAge: "18",
    duration: "2 Seasons",
    year: "",
    genre: "Drama",
    altText: "House of the Dragon",
  },
  {
    viewAllText: "View All",
    sectionName: "Entertainment",
    categoryImage: "/entertainment/category/uandalibi.png",
    bannerImage: "/entertainment/banners/theredking.jpg",
    title: "The Red King",
    description:
      "Chilling folk-horror following police sergeant Grace Narayan, who is sent on a 'punishment posting' to an island with an eerie religion, where the cold case of a missing boy unearths buried secrets.",
    classification: "",
    classAge: "15",
    duration: "6 Episodes",
    year: "",
    genre: "Drama",
    altText: "The Red King",
  },
  {
    viewAllText: "View All",
    sectionName: "Entertainment",
    categoryImage: "/entertainment/category/comedy.png",
    bannerImage: "/entertainment/banners/avenue5.jpg",
    title: "Avenue 5",
    description:
      "Hugh Laurie stars as the captain of luxury space cruiser Avenue 5 in this sci-fi comedy from Armando Iannucci, creator of The Thick Of It. What can possibly go wrong? A Sky...",
    classification: "",
    classAge: "15",
    duration: "2 Seasons",
    year: "",
    genre: "Comedy",
    altText: "Avenue 5",
  },
];
