export const recentlyData = [
  {
    viewAllText: "View All",
    sectionName: "Recently Added",
    categoryImage: "/cinema/category/cinema.png",
    bannerImage: "/cinema/banners/thefallguy.jpg",
    bannerCaller: "/cinema/banners/thefallguy.webp",
    title: "The Fall Guy",
    description:
      "Down-and-out stuntman Ryan Gosling sets out to find the missing star of his ex-girlfriend's blockbuster. Action with Emily Blunt.",
    classification: "S",
    classAge: "12",
    duration: "2h 1m",
    year: "2024",
    genre: "Action",
    altText: "The Fall Guy",
  },
  {
    viewAllText: "View All",
    sectionName: "Recently Added",
    categoryImage: "/cinema/category/cinema.png",
    bannerImage: "/cinema/banners/kungfupanda4.jpg",
    bannerCaller: "/cinema/banners/kungfupanda4.webp",
    title: "Kung Fu Panda 4",
    description:
      "Skadoosh! Jack Black's Po returns to find and train a new Dragon Warrior while a sorceress plans to summon all of his past enemies for revenge.",
    classification: "PG",
    classAge: "S",
    duration: "1h 29min",
    year: "",
    genre: "Animation",
    altText: "Kung Fu Panda 4",
  },
  {
    viewAllText: "View All",
    sectionName: "Recently Added",
    categoryImage: "/cinema/category/cinema.png",
    bannerImage: "/cinema/banners/aquietplace.jpg",
    bannerCaller: "/cinema/banners/aquietplacedayone.webp",
    title: "A Quiet Place: Day One",
    description:
      "Spin-off horror prequel with Lupita Nyong'o and Joseph Quinn. A small group attempts to survive an invasion in New York City.",
    classification: "S",
    classAge: "15",
    duration: "1h 35m",
    year: "2024",
    genre: "Sci-Fi",
    altText: "A Quiet Place: Day One",
  },
  {
    viewAllText: "View All",
    sectionName: "Recently Added",
    categoryImage: "/cinema/category/cinema.png",
    bannerImage: "/cinema/banners/godzillaxkong.jpg",
    bannerCaller: "/cinema/banners/godzillaxkongthenewempire.webp",
    title: "Godzilla X Kong: The New Empire",
    description:
      "Two ancient titans - Godzilla and Kong - clash in an epic battle against an undiscovered threat hidden within our world. Action-packed sci fi",
    classification: "S",
    classAge: "12",
    duration: "1h 49m",
    year: "2024",
    genre: "Action",
    altText: "Godzilla X Kong: The New Empire",
  },
  {
    viewAllText: "View All",
    sectionName: "Recently Added",
    categoryImage: "/cinema/category/cinema.png",
    bannerImage: "/cinema/banners/wonka.jpg",
    bannerCaller: "/cinema/banners/wonka.webp",
    title: "Wonka",
    description:
      "This is the story of how the world's greatest inventor, magician and chocolate-maker became the Willy Wonka we know today.",
    classification: "PG",
    classAge: "S",
    duration: "1h 51m",
    year: "2024",
    genre: "Family",
    altText: "Wonka",
  },
  {
    viewAllText: "View All",
    sectionName: "Recently Added",
    categoryImage: "/cinema/category/cinema.png",
    bannerImage: "/cinema/banners/dune.jpg",
    bannerCaller: "/cinema/banners/dunepart2.webp",
    title: "Dune: Part Two (2024)",
    description:
      "The son of a Duke seeks revenge against the conspirators who destroyed his family. Sci-fi sequel with Timothée Chalamet and Zendaya.",
    classification: "S",
    classAge: "12",
    duration: "2h 39m",
    year: "2024",
    genre: "Action",
    altText: "football",
  },
];
