export const sportsData = [
  {
    viewAllText: "",
    sectionName: "Premier League Highlights",
    categoryImage: "/sports/category/premier_league.png",
    bannerImage: "/sports/banners/premier.jpg",
    title: "Leicester V Man City",
    description:
      "Leicester City play to Manchester City at the King Power Stadium in the Premier League. (29.12)",
    classification: "U",
    classAge: "",
    duration: "3 mins",
    year: "2024",
    genre: "Football",
    altText: "premier",
  },
  {
    viewAllText: "",
    sectionName: "Premier League Highlights",
    categoryImage: "/sports/category/tennis.png",
    bannerImage: "/sports/banners/tennis.jpg",
    title: "Great Britain V Argentina",
    description:
      "British number one Katie Boulter competes in United Cup group-stage action, as the 28-year-old Brit goes up against Argentina's Nadia Podoroska in Sydney. (30.12)",
    classification: "",
    classAge: "0",
    duration: "3 hours",
    year: "",
    genre: "Tennis",
    altText: "tennis",
  },
  {
    viewAllText: "",
    sectionName: "Premier League Highlights",
    categoryImage: "/sports/category/darts.png",
    bannerImage: "/sports/banners/darts.jpg",
    title: "World Darts Championship D12: Afternoon Session",
    description:
      "Ricky Evans and Robert Owen complete the third-round action, while in the last 16, Gerwyn Price plays Jonny Clayton and reigning champion Luke Humphries faces Peter Wright. (29.12)",
    classification: "",
    classAge: "0",
    duration: "4 hours",
    year: "",
    genre: "Darts",
    altText: "darts",
  },
  {
    viewAllText: "",
    sectionName: "Premier League Highlights",
    categoryImage: "/sports/category/nfl.png",
    bannerImage: "/sports/banners/nfl.jpg",
    title: "Cowboys @ Eagles",
    description:
      "Officially out of the playoff reckoning, the 49ers host a Detroit Lions side who recently put together a franchise-record 13th win - staying on top of the NFC in the process. (30.12)",
    classification: "",
    classAge: "0",
    duration: "4 hours",
    year: "",
    genre: "American Football",
    altText: "nfl",
  },
  {
    viewAllText: "",
    sectionName: "Premier League Highlights",
    categoryImage: "/sports/category/cricket.png",
    bannerImage: "/sports/banners/cricket.jpg",
    title: "South Africa V Pakistan",
    description:
      "The fifth and final day of the second Test match between South Africa and Pakistan in Centurion. (30.12)",
    classification: "0",
    classAge: "",
    duration: "8h 30m",
    year: "",
    genre: "Cricket",
    altText: "cricket",
  },
  {
    viewAllText: "",
    sectionName: "Premier League Highlights",
    categoryImage: "/sports/category/football.png",
    bannerImage: "/sports/banners/football.jpg",
    title: "Sheff Utd V West Brom",
    description:
      "Monday Night Football comes from Old Trafford as Manchester United face Newcastle. Ruben Amorim has collected just seven points from his six Premier League games in charge so far...",
    classification: "S",
    classAge: "0",
    duration: "4h 30m",
    year: "",
    genre: "Football",
    altText: "football",
  },
];
